name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}.stridespace.com
          token: ${{ secrets.STRIDESPACE_TOKEN }}
      - name: Push result to Testspace server
        run: |
          testspace results.xml coverage.xml "metrics.log{metrics.csv: a custom metrics}" [url.link]explore.url [non-scripted]"specs/hello.md{1:my exploratory}"
        if: always()